services:
  - type: web
    name: stock-etf-api
    env: docker
    repo: https://github.com/AbdulMutakabbir/etf-stocks.git
    region: oregon
    plan: free
    branch: main
    # rootDir: /**
    dockerCommand: docker compose up --build
    # dockerfilePath: ./DockerFile.api 
    # dockerContext: . 
